require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.whichkey"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.autocommands"
require "user.quickscope"
require "user.hop"
require "user.matchup"
require "user.numb"
require "user.dial"
require "user.colorizer"
require "user.spectre"
require "user.zen-mode"
require "user.neoscroll"
require "user.todo-comments"
require "user.bookmark"
require "user.renamer"
require "user.symbol-outline"
require "user.gitsigns"
require "user.git-blame"
require "user.gist"
require "user.gitlinker"
require "user.session-manager"
-- require "user.surround"  -- use plugin tpope/vim-surround
require "user.notify"
require "user.ts-context"
require "user.registers"
require "user.telescope-file-browser"
require "user.sniprun"
require "user.functions"
require "user.copilot"
require "user.gps"
require "user.illuminate"
require "user.translator"
require "user.markdown" -- none code, some cmd hint
-- require "user.toggleterm"
require "user.floaterm"
require "user.rnvimr"

-- markdown_filetype_imap
-- require "user.markdown_insert_map"
vim.cmd [[
  augroup insert_comma_mapkeys
    autocmd!
    autocmd filetype markdown :lua require "user.whichkey_comma"
  augroup END
]]
